spring.application.name=Git-Practices
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/gitdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dmnt@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.servlet.multipart.enabled=true

# Removed the MySQL8Dialect line
spring.jpa.open-in-view=false