spring.application.name=Git-Practices
spring.datasource.url=jdbc:mysql://localhost:3306/your_db
spring.datasource.username=db_user
spring.datasource.password=your_password_here
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.file.name=logs/test.log

spring.servlet.multipart.enabled=true

# Removed the MySQL8Dialect line
spring.jpa.open-in-view=false